from classes.structures.Atribuicao import Atribuicao
from classes.structures.Cabecalho import Cabecalho
from classes.structures.Escreva import Escreva
from classes.structures.Indice import Indice
from classes.structures.InicializacaoDeVariaveis import InicializacaoDeVariaveis
from classes.structures.Leia import Leia
from classes.structures.Repita import Repita
from classes.structures.Retorna import Retorna
from classes.structures.Se import Se
